name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Lint, Format, and Build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Formatting
        run: pnpm run format:check

      - name: Run ESLint (Workspace)
        run: pnpm run lint

      - name: Build Client
        run: pnpm run build
